<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NoDistortionWatermark\Auxiliary\MapboxTileWriterWm.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NetTopologySuite" Version="2.5.0" />
    <PackageReference Include="NetTopologySuite.Features" Version="2.1.0" />
    <PackageReference Include="NetTopologySuite.IO.VectorTiles" Version="1.0.3" />
    <PackageReference Include="NetTopologySuite.IO.VectorTiles.Mapbox" Version="1.0.3" />
    <PackageReference Include="protobuf-net" Version="3.1.26" />
  </ItemGroup>

</Project>
