name: dotnet

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./MvtWatermark

    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal